# Generated by Django 4.1 on 2022-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peserta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("angkatan", models.IntegerField()),
                ("jurusan", models.TextField()),
                ("divisi_sbf", models.TextField()),
            ],
        ),
    ]
